---
title: "Aggregation Queries - Flights"
output: html_document
---

In this example we will calculate the number of flights per year, month, and day in the `nycflights13` dataset. We will first export the dataset as JSON, upload it to our SolveBio account, then query it from SolveBio to aggregate for the values we need.

```{r}
# Install packages if you do not have them already
# install.packages("nycflights13")
# install.packages("jsonlite")
# install.packages("solvebio")

library(nycflights13)
library(jsonlite)
library(solvebio)

# log into SolveBio
login(api_host = 'https://api.solvebio.com', api_key = 'your_key_here')
```

# Data Export & Import

```{r}
# Save the flights dataset to JSON
stream_out(flights, con = file("flights.json"))

# Upload it to your SolveBio personal vault
vault <- Vault.get_personal_vault()
object <- Object.upload_file("flights.json", vault$id, '/')

# TODO: Replace this with vault$full_path (coming soon)
vault_full_path <- paste(vault$account_domain, ":", vault$name, ":", sep="")
dataset_full_path <- paste(vault_full_path, "/flights.dataset", sep="")
# [1] "username:user-1234:/flights.dataset"

flights <- Dataset.get_or_create_by_full_path(dataset_full_path)

# Import the dataset and wait until done
import <- DatasetImport.create(dataset_id=flights$id,
                               object_id=object$id)
while(import$status == "queued" || import$status == "running") {
    import <- DatasetImport.retrieve(import$id)
    cat(import$status, sep="\n")
    Sys.sleep(3)
}

```

# Aggregation Querying

```{r}
# create an empty dataframe to hold the results
flights_df <- data.frame(year = character(0), 
                         month = character(0), 
                         day = character(0), 
                         flights = numeric(0) )

# get the years in the dataset
year_facets <- list(year__histogram=list(interval=1))
per_year <- Dataset.facets(id = flights$id, facets=year_facets)[['year__histogram']][, 1]

# iterate over the years
for(year in per_year){
    # create a filter list for the next query
    year_filter <- list(list('year', paste(year)))
    
    # get months per the given year
    month_facets <- list(month__histogram=list(interval=1))
    per_month <- Dataset.facets(id = flights$id, 
                             filters = year_filter, 
                             facets = month_facets)[['month__histogram']][,1]
    
    # iterate over months
    for(month in per_month){
        
        # create a new list of filters to use
        month_filter <- list(year_filter[[1]], list('month', paste(month)))
        
        # get the facet matrix for days in the month
        days_facets <- list(day__histogram=list(interval=1))
        days_matrix <- Dataset.facets(id = flights$id, 
                                      filters = month_filter, 
                                      facets = days_facets)[['day__histogram']]
        
        # convert the matrix to named numeric vector
        days <- setNames(object = as.numeric(days_matrix[,2]),
                         nm = days_matrix[,1])
        
        # iterate over the days in the month
        for(i in seq_along(days)){
            # get the values for that day
            num <- days[i]
            day <- names(days[i])
            
            # make a single entry df
            df <- data.frame(year = year,
                             month = month, 
                             day = day,
                             flights = num)
            
            # add it to the original df
            flights_df <- rbind(flights_df, df)
        }
    }
}

print(flights_df)

# year month day flights
# 1 2013     1   1    1684
# 2 2013     1   2    1886
# 3 2013     1   3    1828
# 4 2013     1   4    1830
# 5 2013     1   5    1440
# 6 2013     1   6    1664
```
