name: R

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        r-version: [3.6, 4.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install solvebio package and dependencies
        run: |
          install.packages("solvebio")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Run tests
        run: make test