name: R

on: push

jobs:
  solvebio-R:
    runs-on: ubuntu-20.04
    env:
      SOLVEBIO_API_HOST: ${{ secrets.QUARTZBIO_API_HOST }}
      SOLVEBIO_API_KEY: ${{ secrets.QUARTZBIO_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install curl
        run: |
          sudo apt-get install libcurl4-openssl-dev r-base libfontconfig1-dev libharfbuzz-dev libfribidi-dev
          R -q -e "install.packages(c('curl'))"
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "httr", "jsonlite", "devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check package
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
      - name: Run tests
        run: |
          make test
